# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Portable, single-binary Go IDE built on Neovim"
  homepage "https://github.com/meerkat-b/burrow"
  version "0.0.7"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.7/burrow_0.0.7_darwin_amd64.tar.gz"
      sha256 "c5f10791ab18a9843ce9ea7466989bf7acff041a552a862d35e7aa0d37572c38"

      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.7/burrow_0.0.7_darwin_arm64.tar.gz"
      sha256 "943c2ce058156a8d37f1cf9779d0cd26e9702f5f5a8ba0d3d35b70aba258b4dd"

      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.7/burrow_0.0.7_linux_amd64.tar.gz"
      sha256 "e60218fc487d7ec76f96f872cce993f8d7c4dc5ef25c7536d335cd6a30f8505d"
      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.7/burrow_0.0.7_linux_arm64.tar.gz"
      sha256 "417b82bf4620d888a4541a62ffb78b80a7f8e4abddcf23328c655ec31cd370bd"
      define_method(:install) do
        bin.install "burrow"
      end
    end
  end
end
