# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burrow < Formula
  desc "Portable, single-binary Go IDE built on Neovim"
  homepage "https://github.com/meerkat-b/burrow"
  version "0.0.6"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.6/burrow_0.0.6_darwin_amd64.tar.gz"
      sha256 "b3e6de8cc336a9b66a23de75f4db940e56267e055f8cf1c07d86f1296af5c1df"

      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.6/burrow_0.0.6_darwin_arm64.tar.gz"
      sha256 "5fdcfc34928ab916ead648fa68331ebfac7b253325c50c6da1084ccff9d16541"

      define_method(:install) do
        bin.install "burrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.6/burrow_0.0.6_linux_amd64.tar.gz"
      sha256 "2d5158905df1a4af9633e57f4b9c4cd1dbc89feff8f2956233ac70ae95593f18"
      define_method(:install) do
        bin.install "burrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/meerkat-b/burrow/releases/download/v0.0.6/burrow_0.0.6_linux_arm64.tar.gz"
      sha256 "13e68e7343a034a88e9118cdcc07cc968fc2955c0c5c6f6fbeb022459a09acaf"
      define_method(:install) do
        bin.install "burrow"
      end
    end
  end
end
